### ISSUE TITLE
Incorrect directory permissions after accidentally running as sudo

### ISSUE THREAD

**Issue by Caleb1994** [baskerville/owlman#26]
If you mistakenly run `owlman` with sudo, you will get an error from `makepkg` stating that you cannot run `makepkg` as root. This makes sense, and should happen. The issue is that `owlman` downloads the AUR package to /tmp/owlman-aur as root. If you then try to install the same package without sudo (which is expected in this case), `makepkg` will fail because you do not own the directory (root does).

A simple quick fix in that situation is to just `chown` the specific directory (say, '/tmp/owlman-aur/google-chrome` for the google-chrome package) or to remove it completely, and then run the install again.

I think the simplest fix would be for owlman to check that you are not running as root before doing any of the wrapping.

**Comment by baskerville** [comment]
Thanks.
